[workspace]
members = [
  "crates/trycp_server",
  "ts/test/fixture/zomes/coordinator",
  "ts/test/fixture/zomes/integrity",
]
resolver = "2"

[workspace.dependencies]
hdi = "0.3.6"
hdk = "0.2.6"
serde = "1"

[profile.dev]
opt-level = "z"
