[workspace]
members = [
  "crates/trycp_server",
  "ts/test/fixture/zomes/coordinator",
  "ts/test/fixture/zomes/integrity",
]

[workspace.dependencies]
hdi = "0.4.0-beta-dev.5"
hdk = "0.3.0-beta-dev.7"
serde = "1"

[profile.dev]
opt-level = "z"
