[workspace]
members = [
  "crates/trycp_server",
  "ts/test/fixture/zomes/coordinator",
  "ts/test/fixture/zomes/integrity",
]

[workspace.dependencies]
hdi = "0.3.1-beta-dev.0"
hdk = "0.2.1-beta-dev.0"
serde = "1"

[profile.dev]
opt-level = "z"
