[workspace]
members = [
  "crates/trycp_server",
  "ts/test/fixture/zomes/coordinator",
  "ts/test/fixture/zomes/integrity",
]
resolver = "2"

[workspace.dependencies]
hdi = "0.4.0-beta-dev.16"
hdk = "0.3.0-beta-dev.20"
serde = "1.0.181"

[profile.dev]
opt-level = "z"
