[workspace]
members = [
  "crates/trycp_server",
  "ts/test/fixture/zomes/coordinator",
  "ts/test/fixture/zomes/integrity",
]
resolver = "2"

[workspace.dependencies]
hdi = "0.4.1"
hdk = "0.3.1"
serde = "1.0.192"

[profile.dev]
opt-level = "z"
