[package]
name = "trycp_server"
version = "0.0.100-alpha0"
description = "conductor provisioner for tyrorama"
license = "CAL-1.0"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
homepage = "https://github.com/holochain/tryorama"
documentation = "https://github.com/holochain/tryorma/crates/trycp_server"
repository = "https://github.com/holochain/tryorma"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
# TODO: Remove me
in_stream = { version = "=0.0.52-alpha2", git = "https://github.com/holochain/holochain-rust" }

base64 = "=0.10.1"
env_logger = "0.7.0"
jsonrpc-core = "14.0"
jsonrpc-ws-server = "14.0"
lazy_static = "=1.4.0"
log = "0.4.8"
nix = "=0.14.1"
regex = "=1.1.2"
reqwest = "=0.9.11"
serde = "=1.0.104"
serde_derive = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
snowflake = "=1.3.0"
structopt = "=0.2.18"
structopt-derive = "=0.2.18"
tempfile = "=3.0.7"
url2 = "=0.0.4"
