[package]
name = "trycp_server"
version = "0.0.100-alpha0"
description = "conductor provisioner for tryorama"
license = "CAL-1.0"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
homepage = "https://github.com/holochain/tryorama"
documentation = "https://github.com/holochain/tryorma/crates/trycp_server"
repository = "https://github.com/holochain/tryorma"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2021"

[dependencies]
futures = "0.3.14"
nix = "0.20.2"
once_cell = "1.5.0"
parking_lot = "0.10.0"
reqwest = "0.11.3"
rmp-serde = "0.14.3"
serde = { version = "1.0.104", features = ["derive"] }
serde_bytes = "0.11.0"
slab = "0.4.0"
snafu = "0.6.10"
structopt = "0.2.18"
structopt-derive = "0.2.18"
tokio = { version = "1.8.4", features = ["macros", "rt-multi-thread", "process", "fs"]}
tokio-tungstenite = "0.14.0"
url = "2.1.0"
