[package]
name = "trycp_server"
version = "0.0.100-alpha0"
description = "conductor provisioner for tryorama"
license = "CAL-1.0"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
homepage = "https://github.com/holochain/tryorama"
documentation = "https://github.com/holochain/tryorma/crates/trycp_server"
repository = "https://github.com/holochain/tryorma"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
# TODO: Remove me
in_stream = { version = "=0.0.52-alpha2", git = "https://github.com/holochain/holochain-rust" }

base64 = "0.13.0"
crossbeam = "0.8.0"
jsonrpc-core = "14.0"
jsonrpc-ws-server = "14.0"
nix = "=0.14.1"
once_cell = "1.5.0"
parking_lot = "0.10.0"
reqwest = "=0.9.11"
rmp-serde = "0.14.3"
serde = "=1.0.104"
serde_bytes = "0.11.0"
serde_derive = "=1.0.104"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
slab = "0.4.0"
structopt = "=0.2.18"
structopt-derive = "=0.2.18"
url = "2.1.0"
url2 = "=0.0.4"
ws = "0.9"
