[package]
name = "trycp_server"
version = "0.0.100-alpha0"
description = "conductor provisioner for tyrorama"
license = "CAL-1.0"
keywords = ["holochain", "holo", "p2p", "network", "simulation"]
homepage = "https://github.com/holochain/tryorama"
documentation = "https://github.com/holochain/tryorma/crates/trycp_server"
repository = "https://github.com/holochain/tryorma"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
edition = "2018"

[dependencies]
in_stream = { version = "=0.0.52-alpha2", git = "https://github.com/holochain/holochain-rust" }
structopt-derive = "=0.2.18"
structopt = "=0.2.18"
jsonrpc-core = "14.0"
jsonrpc-ws-server = "14.0"
serde_json = { version = "=1.0.47", features = ["preserve_order"] }
serde_derive = "=1.0.104"
serde = "=1.0.104"
nix = "=0.14.1"
reqwest = "=0.9.11"
url2 = "=0.0.4"
