[package]
name = "trycp_api"
version = "0.0.100-alpha0"
license = "CAL-1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.192", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0.117"
