name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2

    - name: Cache nix env take N+1
      uses: actions/cache@v2
      with:
        path: |
          # See https://github.com/actions/cache/pull/726
          /nix/store/**
          # Missing something?
          /nix/var/nix/*/*
          /nix/var/nix/db/*
          /nix/var/nix/db/*/**
          !/nix/var/nix/daemon-socket/socket
          !/nix/var/nix/userpool/*
          !/nix/var/nix/gc.lock
          !/nix/var/nix/db/big-lock
          !/nix/var/nix/db/reserved
        key: ${{ runner.os }}-nix-store

    - name: Use Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11

    # - name: Configure Nix substituters
    #   run: |
    #     set -xe
    #     mkdir -p ~/.config/nix/
    #     cp ./.github/nix.conf ~/.config/nix/

    - uses: cachix/cachix-action@v10
      with:
        name: holochain-ci

    - name: Cache Rust builds
      id: cache-rust
      uses: actions/cache@v3
      env:
        cache-name: cache-rust
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: |
          ./.cargo
          ./.target
          ./crates/trycp_server/target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - name: Run all tests
      run: nix-shell --pure --run "./run-test.sh"
