name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch source code
      uses: actions/checkout@v2

    - name: Use Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11

    - uses: cachix/cachix-action@v10
      with:
        name: holochain-ci

    - name: Cache Rust builds
      id: cache-rust
      uses: actions/cache@v3
      env:
        cache-name: cache-rust
      with:
        path: |
          ./.cargo
          ./.target
          ./crates/trycp_server/target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Run all tests
      run: nix-shell --pure --run "./run-test.sh"
