name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out source code
      uses: actions/checkout@v2

    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11

    - name: Set up cachix
    - uses: cachix/cachix-action@v10
      with:
        name: holochain-ci

    - name: Cache TryCP server build
      id: cache-trycp-server
      uses: actions/cache@v3
      env:
        cache-name: cache-trycp-server
      with:
        path: crates/trycp_server/target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('crates/trycp_server/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Run all tests
      run: nix-shell --pure --run "./run-test.sh"
