name: Run tests

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  test:
    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.platform }}

    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11

    - name: Set up cachix
      uses: cachix/cachix-action@v10
      with:
        name: holochain-ci

    - name: Cache TryCP server build
      uses: actions/cache@v3
      env:
        cache-name: cache-trycp-server
      with:
        path: |
          .cargo
          crates/trycp_server/target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('crates/trycp_server/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('crates/trycp_server/Cargo.lock') }}

    - name: Cache test zome build
      uses: actions/cache@v3
      env:
        cache-name: cache-test-zomes
      with:
        path: |
          .cargo
          target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}

    - name: Build TryCP server and test hApp and run tests
      id: build-and-test
      run: nix-shell --pure --run "./run-test.sh"

    - name: Setup tmate session if build and test run failed
      if: steps.build-and-test.outcome == 'failure'
      uses: mxschmitt/action-tmate@v3
