name: Run tests

on:
  pull_request:
  push:
    branches: [develop, main]

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out source code
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v27

      - name: Set up cachix
        uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Build Nix packages
        run: nix develop -c $SHELL -c "echo Nix packages built"

      - name: Restore TryCP server build
        uses: actions/cache/restore@v4
        with:
          path: crates/trycp_server/target
          key: ${{ runner.os }}-build-trycp-${{ hashFiles('crates/trycp_server/Cargo.lock') }}

      - name: Build TryCP server
        run: nix develop -c $SHELL -c "./build-trycp.sh"

      - name: Save TryCP build to cache
        uses: actions/cache/save@v4
        with:
          path: crates/trycp_server/target
          key: ${{ runner.os }}-build-trycp-${{ hashFiles('crates/trycp_server/Cargo.lock') }}

      - name: Restore test zome build
        uses: actions/cache/restore@v4
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-test-zomes-${{ hashFiles('Cargo.lock') }}

      - name: Build test zomes
        run: nix develop -c $SHELL -c "./build-fixture.sh"

      - name: Save test zome build to cache
        uses: actions/cache/save@v4
        with:
          path: |
            .cargo
            target
          key: ${{ runner.os }}-build-test-zomes-${{ hashFiles('Cargo.lock') }}

      - name: Install JS packages
        run: nix develop -c $SHELL -c "npm ci"

      - name: Run tests
        run: nix develop -c $SHELL -c "npm t"

      - name: Build trycp-server package
        run: nix build .#trycp-server

      - name: Setup tmate session if build or test run failed
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 100
